packages/meteor/src/MeteorDataFetcher.ts
packages/meteor/src/MeteorTableImpl.ts
packages/meteor/src/MeteorTableOperations.ts
packages/meteor/src/MethodDataFetcherImpl.ts
packages/meteor/src/index.ts
packages/moxb/src/table/TableImpl.ts

This PR is a prerequisite for https://app.zenhub.com/workspace/o/go-e/ves/issues/77.
Besides some minor improvements, this PR introduces the concept of `invalidateData` on the `MeteorDataFetcher` interface, which method should be used to signal that the currently displayed data is no longer correct.
In the implementation, `MeteorDataFetcherImpl` implements this function by running the `runDataFetcherFunction()`
That is all nice, but we have to be able to trigger this from `MeteorTableImpl` for which I added a new interface called `MeteorTableOperations` to implement and it calls the `this.tableFetcher.invalidateData();`
I think that this invalidateData does not belong to the `Table` interface itself, so a separate interface was needed.
@scharf : What do you think?

Add invalidateData() hook for meteor tables

---

package-lock.json
packages/moxb/package.json
packages/moxb/src/routing/url-arg/UrlArgTypes.ts
packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeOrderedStringArray.test.ts
packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeUnorderedStringArray.test.ts

`ves` does not work with the master version of `moxb`, because it complains about `lodash.memoize`. This problem does probably not happen, if we would install `moxb` the normal way. But the combination of `lerna` and linked packages causes problems.
However, I was looking why `moxb` needs `lodash.memoize`: it is needed by `UrlArgTypes.ts`.
Looking at the tests I discovered some inconsistencies: 
- sometimes the test requires the result of `parse()` to be the same, and sometimes it is not the same
- for unordered arrays, the order should not matter when `parse()` is called (the result should always be the same)
- the `defaultValue` was ignored for attray types
So, I thought, I would fix it (see PR #47), but that turns out to be more complicated. Therefore, I decided to drop the constraint …

Args parser does not use memorize

---

Makefile
admin/node-installation/install.sh

In some networking circumstances, wget will simply hang indefinitely,
while curl simply works.
I didn't have time to debug this, but replacing wget with curl
solves the problem in 100% of the cases.

Replace wget with curl

---

examples/src/app/AppRouterAnt.tsx
examples/src/menus/DetailDisplayer.tsx
examples/src/menus/MoreMenusAnt.tsx
examples/src/menus/SubMenu.tsx
examples/src/store/Store.ts
examples/src/store/UrlStore.ts
examples/src/store/UrlStoreImpl.ts
packages/antd/src/not-antd/LocationDependentArea.tsx
packages/moxb/src/routing/TokenManager.ts
packages/moxb/src/routing/TokenManagerImpl.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandler.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts
packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandler.ts
packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandlerImpl.ts
packages/moxb/src/routing/url-arg/UrlTokenImpl.ts

... so that it can work in all the menus, not only in the top menu.
The main idea is that instead of registering the path token mapping patterns manually with the token manager, we can just let the `LocationDependentArea` component do the registration. (That component has all the required information about the navigation context.)
Regardless of this, all the information lives in the model, except the mappings, which we load from the menu structure. 
There are no side-effects from render; we are using `componentDidMount` and `componentWillUnmount` for hooks.
The application-facing API doesn't change, except the constructor parameters of the token manager.
(Please merge #57 and #58 first, then rebase this one.)

Improve the path token matching API

---

packages/antd/src/ActionAnt.tsx
packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap
packages/moxb/src/action/Action.ts
packages/moxb/src/action/ActionImpl.ts

This changes adds a pending state to actions.
- When defining an action, one can can specify a "pending" function.
- When this "pending" function returns true
- A button bound to this action will display a spinner
- A button bound to this action won't be clickable.

Add pending state to actions

---

packages/antd/src/routing/MultiStepProcessAnt.tsx
packages/antd/src/routing/index.ts
packages/moxb/src/routing/MultiStepProcess.ts
packages/moxb/src/routing/index.ts

The steps are defined as a state-space.
The process is stored in an [URL]Arg.
The list of steps is shown at the top,
and the content (according to the current step)
is shown on the bottom.
We can also handle the finished and failed states.

Add a widget for indicating process using antd steps

---

packages/meteor/src/Bit.ts
packages/meteor/src/MeteorAction.ts
packages/meteor/src/index.ts

This is a continuation of https://github.com/moxb/moxb/pull/71, so please merge that first.
The main idea here is that it should be trivial to define a (moxb) Action that is backed by a Meteor method,
so that we have type safety on the input and on the output side, we can't misspell the method name, and
we also get automatic integration for things like indicating the pending state on buttons, etc.

Support for creating Actions backed by Meteor methods

---

packages/antd/src/OneOfAnt.tsx
packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap

It turns out that when we define elements inside radio groups,
we are not supposed to pass in a "checked" property to these elements.
Instead, we should pass in "value" to the group itself, and then it will
calculate the checked state of the elements automatically.
We missed this earlier because the two approaches produce almost identical
behavior, expect in situations when the state changes quickly.
In those cases, specifying checked directly can lead to inconsistent
results.

Fix incorrect use of Ant radio groups

---

packages/antd/src/routing/NavMenuBarAnt.tsx

The problem was that `NavMenuBarAnt` kept a state and did not react properly to property changes. In particular, if something has changed in user, the `getUserMenu` is called correctly but `NavMenuBarAnt` did to react to the changes, because it created the `LocationDependentStateSpaceHandler` only in the constructor.
The problematic part of `getUserMenu` is here:
```
export const getUserMenu = (user?: User): StateSpace<UIFragment, UIFragmentSpec, PermData> => [
...
{
displayOnly: true,
hidden: !user || !user!.currentOrganization,
key: 'myOrganization',
pathTokens: ['organizations', user ? (user.currentOrganization || { _id: '' })._id : '_', 'edit'],
label: tr('Account.menu.actions.organization', 'Settings for {{name}}', () => ({
...user!.currentOrganization,
})),
},
...
]
````
Every time …

make nav bar reactive

---

packages/antd/src/ActionAnt.tsx
packages/antd/src/BindAnt.tsx

This PR adds the option to prevent event propagation for `ActionAnt` components.
Note that in the previous implementation the handling of the pending operation was different for `ActionButtonAnt` and `ActionSpanAnt`.
I left that difference untouched, however maybe that was a bug itself.

Stop event propagation for action click handlers

---

packages/moxb/src/routing/TokenManager.ts
packages/moxb/src/routing/TokenManagerImpl.ts
packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts
packages/moxb/src/routing/location-manager/LocationManager.ts
packages/moxb/src/routing/location-manager/index.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandler.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts
packages/moxb/src/routing/location-state-space/__tests__/LocationDependentStateSpaceHandlerImpl.test.ts
packages/moxb/src/routing/url-arg/AnyUrlArgImpl.ts
packages/moxb/src/routing/url-arg/InMemoryArgImpl.ts
packages/moxb/src/routing/url-arg/UrlArg.ts
packages/moxb/src/routing/url-arg/UrlArgImpl.ts
packages/moxb/src/routing/url-arg/UrlTokenImpl.ts

... to accept (optional) callbacks instead of returning
Promises (which can optionally be used), since tslint
really _hates_ the lying over left-over promises.
This is a fully internal refactoring, no features have been added or changed.

Modify the "soft" navigation APIs

---

packages/moxb/src/bind/BindImpl.ts
packages/moxb/src/bind/__tests__/BindImpl.test.ts
packages/moxb/src/form/FormImpl.ts
packages/moxb/src/form/__tests__/Form.test.ts

There was a problem that same error string appeared multiple times in the UI.

Fix: do not report errors more than once

---

packages/antd/src/not-antd/rootOrDetails.tsx
packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts
packages/moxb/src/routing/location-manager/LocationManager.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts

... which has sneaked into the system when we started to
dynamically re-create the state space handlers.
Now each change interceptor must be able to produce a unique ID
for the component that it is representing, and newer iterations
of the same interceptor replace the old one's registration, instead
of being added at the end of the list.
This make sure that we always have only one interceptor from
each kind, and thus eliminates the duplicated questions.

[VS-175] Eliminate duplicate change interceptors

---

packages/meteor/src/MeteorSubscription.ts
packages/meteor/src/MeteorSubscriptionImpl.ts

- Add an `errorMessage` field, for human-readable messages
- Rename `error` to `errors`, for capturing multiple errors.
- Remove the `isSubscriptionReady` field, since we should use
`pending` instead (which also checks for errors)

Improve meteor subscriptions API

---

packages/moxb/src/form/Form.ts
packages/moxb/src/form/FormImpl.ts
packages/moxb/src/form/__tests__/Form.test.ts
packages/moxb/src/value/Value.ts
packages/moxb/src/value/ValueImpl.ts
packages/moxb/src/value/__tests__/ValueImplTest.test.ts

- Introducing a new optional configuration option for values: `isGiven`.
When configured, this function will be called to test whether or not
the current value is considered to be a real value.
- Introducing the `isGiven` value on the `Value` interface. This will be true
if the value has a valid value. By default, this means !!value,
but this can be overridden by configuring the `isGiven` function,
as mentioned above
- Introducing the `hasMissingRequired` field on the `Form` interface.
This will be true if some required fields are missing.
- Change the behavior of form: when trying to save, earlier we detected
missing required values by comparing initial values with the initial values.
This was wrong in the cases when there was a non-null initial value.
Now we are always using the new …

Expand the Value and Form API

---

ChangeLog.md
packages/moxb/src/bind/BindImpl.ts
packages/moxb/src/bind/__tests__/BindImpl.test.ts
packages/moxb/src/decision/index.ts
packages/moxb/src/index.ts
packages/moxb/src/keyboard-shortcuts/KeyboardShortcutsManagerImpl.ts

... so that it can be more easily reused by other components.
There is no new code, this is purely moving some code around.

Separate the decision-related code into a new module

---

ChangeLog.md
packages/antd/src/routing/NavMenuBarAnt.tsx

This is a trivial change, just passing on a parameter that is already being passed on at other places.

Support for passing on class names for submenus

---

ChangeLog.md
packages/antd/src/ManyOfAnt.tsx
packages/antd/src/OneOfAnt.tsx
packages/antd/src/__tests__/__snapshots__/ManyOfAnt.test.tsx.snap
packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap

There was a problem with displaying the placeholder text correctly in OneOfSelect and ManyOfSelect ant design components.
Fixes: [https://goessntl.atlassian.net/browse/VS-238](https://goessntl.atlassian.net/browse/VS-238)

Fix placeholder text display

---

packages/antd/src/OneOfAnt.tsx
packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap
packages/moxb/src/one-of/OneOf.ts
packages/moxb/src/one-of/OneOfImpl.ts

- Add a new field to the `OneOf` interface, for getting the current choice's title (if any)
- Add `readOnly` support to `OneOfButtonAnt` and `OneOfSelectAnt`.
(The prop was already there, just didn't do anything.)

OneOf improvements

---

ChangeLog.md
examples/src/app/ApplicationAnt.tsx
packages/antd/src/PollingUpdaterAnt.tsx
packages/antd/src/index.ts

The `PollingUpdaterAnt` is a widget for displaying some data that is periodically updated.
The update function must be supplied by the application.
The polling will be managed by this widget.
The polling frequency can be configured.
When hovering the pointer above the content, we will see some information about when the data was updated last. Immediate clicking is available by clicking.

Add PollingUpdaterAnt for displaying periodically updated content

---

packages/moxb/src/modal/ModalImpl.ts

On the `Modal` interface there is an `onOpen` function, however we didn't support it because `antd` doesn't support it.
This PR adds a simple way to simulate this `onOpen` functionality. This is prerequisite for job-multi-creation

Add onOpen handle to ModalOptions

---

ChangeLog.md
packages/antd/src/not-antd/LocationDependentArea.tsx

When using the `mountAll` option with a menu, rendering of "fallback"
content was broken. (Ie. the thing that is shown when a non-existent
item is requested from the menu.)
Also, we were rendering _all_ the sub-states, not only those that were
currently available, considering the conditions.
These problems have been fixed.

Fix `mountAll` option

---

ChangeLog.md
packages/antd/src/routing/NavRadioButtonsBarAnt.tsx

`NavRadioButtonBarAnt` used to take and `extras` prop (for a list of extra components to display),
but this caused some problems, because React doesn't like rendering components from a list
without unique keys. (And since the components can come from different sources, there is no way
to reliably assign keys.) Reducing it to accepting a single component.
This causes a breaking API change (for those apps that use `NavRadioButtonsBarAnt` with extra widgets).
I will create a matching PR for `ves`.

NavRadioButtonsBarAnt: accept only one extra widget

---

packages/moxb/src/modal/Modal.ts

This is both supported by antd and semantic-ui.

Allow using a ReactNode component in modal.header.

---

ChangeLog.md
examples/src/menus/MoreMenusAnt.tsx
examples/src/menus/SubMenu.tsx
package-lock.json
packages/antd/src/not-antd/LocationDependentArea.tsx
packages/antd/src/not-antd/rootOrDetails.tsx
packages/antd/src/routing/NavTabBarAnt.tsx
packages/moxb/package-lock.json
packages/moxb/package.json
packages/moxb/src/routing/index.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandler.ts
packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts
packages/moxb/src/routing/location-state-space/index.ts
packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandler.ts
packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandlerImpl.ts
packages/moxb/src/routing/navigable.ts

... with two features:
- Earlier, we could only have one hook for a give sub-state.
However, it's possible that a page has multiple components
for the same sub-state, and more than one of those can
require navigation hooks. So we introduced an optional
component name that can be passed in when registering hooks.
This makes it possible to handle hooks for different components
independently.
- Also support unregistering hooks.
- Add support for testing active active status of the current sub-state
- Add support for describing navigation tree path recursively (for debugging)
This change is fully backward compatible, since the newly introduced parameter is optional.
(So existing application code works without any modification.)
Closes [VS-139].

[VS-139] Extends the NavControl interface

---

packages/moxb/src/routing/index.ts
packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts
packages/moxb/src/routing/location-manager/index.ts

(The previous syntax still works, this is only an additional possibility.)

Extend API: more ways to build URLs

---

packages/antd/src/FormItemAnt.tsx
packages/antd/src/__tests__/__snapshots__/FormItemAnt.test.tsx.snap

... since apparently, ID is now obsolete.
See https://github.com/ant-design/ant-design/pull/16278/files for the upstream change.

Update our code to use htmlFor on Form.Item

---

ChangeLog.md
packages/meteor/src/MeteorMethod.ts
packages/moxb/src/index.ts
packages/moxb/src/routing/tokens.ts
packages/moxb/src/util/debugLog.ts

The idea is the following:
- You can use `getDebugLogger(prefix, debug)`  to get a logger object (typically at the beginning of a function)
- When calling this function, we specify whether we are in debug mode, and also an (optional) prefix to use for logging
- Afterwards, you can use `logger.log()` as a drop-in replacement for `console.log()` (It also has `debug()`, `info()`, `warn()` and `error()`, just like console.)
- When debug mode is off, there is no output; when debug mode is on, we dump everything to the console.

Added a small utility for creating conditional (debug) loggers

---

ChangeLog.md
packages/moxb/src/cached-evaluator/CachedEvaluator.ts
packages/moxb/src/cached-evaluator/CachedEvaluatorImpl.ts
packages/moxb/src/cached-evaluator/CachedOptionalValue.ts
packages/moxb/src/cached-evaluator/CachedOptionalValueImpl.ts
packages/moxb/src/cached-evaluator/CachedValue.ts
packages/moxb/src/cached-evaluator/CachedValueImpl.ts
packages/moxb/src/cached-evaluator/index.ts
packages/moxb/src/cached-evaluator/readme.md
packages/moxb/src/index.ts

The purpose of these utilities is to provide a utility to cache a value
(or more values) that come from an outside source, and we want to periodically
update, but also cache for a while, because of the cost of updating.
The idea is that we don't want to check the value more than, say, once in
every five minutes. We have a function for actually getting the value,
and we wrap this caching object around that function.
The users of the value will call `get()` on this caching object, which will
either call the _real_ function to get the data (if it's time), or just
get the value from the cache.

Add cached value utility

---

ChangeLog.md
packages/antd/src/BindAnt.tsx
packages/antd/src/FormItemAnt.tsx

When we have a BoolAnt, and we put it into a form via BoolFormAnt,
then the label is displayed twice: before and after the checkbox.
Since we usually don't want that, we have already set up FormItemAnt
so that the "label" prop can be overridden, so that we are not forced
to display the label coming directly for the operation.
The current change extends this support to the "help" field of the operation.
The help is displayed in a popup when the user hovers above the small (?) besides
the label; basically it's an extension of the label. With this change, it can be
overridden the same way as it works with the label.

Make it possible to override the help on form items

---

ChangeLog.md
packages/antd/src/SliderAnt.tsx

Antd divides the grid into 24 pieces instead of 16 pieces (which is the bootstrap standard)

Small fix for SliderAnt spacing

---

ChangeLog.md
packages/moxb/src/routing/navigation-references/NavRefImpl.ts
packages/moxb/src/routing/url-schema/NativeUrlSchema.ts
packages/moxb/src/routing/url-schema/UrlSchema.ts

Up to now, the `NativeUrlSchema` only worked if our app lives at the root of the website.
This change enables it to be used in other situations, when our app is embedded under some path. (Ie. /app )

NativeUrlSchema: support being embedded within some path

---

ChangeLog.md
packages/html/src/NavLink.tsx

The trick here is that if the `target` argument is specified on the link, we shouldn't install a click handler: just let the browser do what it would normally do.

Fix support for the target HTML arg on NavLink and friends

---

ChangeLog.md
packages/antd/src/routing/NavLinkButtonAnt.tsx

When the target HTML attribute is set, we shouldn't use a button and a click handler
for navigation, but we should use NavLink to render an actual HTML link instead,
and let the browser handle the navigation.

Fix the handling of the target attribute on NavLinkButtonAnt

---

ChangeLog.md
packages/html/src/Anchor.tsx

When an Anchor is disabled, the cursor should be set appropriately,
and we shouldn't react to clicks.

Fix the disabled arg on Anchor

---

ChangeLog.md
packages/antd/src/routing/BoundNavLinkButtonAnt.tsx
packages/html/src/BoundNavLink.tsx
packages/moxb/src/routing/linking/BoundLink.ts
packages/moxb/src/routing/linking/BoundLinkImpl.ts

This adds the help, enabled and disabled options to the configuration of BoundLink.
It all works exactly the same is it works for Action.
* * *
The depends on https://github.com/moxb/moxb/pull/209; please merge that first, then rebase this one.
(Dropping the first commit automatically.)

Enhance BoundLink with help, enabled, disabled 

---

ChangeLog.md
examples/src/app/ApplicationAnt.tsx
packages/antd/src/BoolAnt.tsx
packages/antd/src/DatePickerAnt.tsx
packages/antd/src/ManyOfAnt.tsx
packages/antd/src/NumericAnt.tsx
packages/antd/src/OneOfAnt.tsx
packages/antd/src/SliderAnt.tsx
packages/antd/src/TagAnt.tsx
packages/antd/src/TextAnt.tsx
packages/antd/src/TimePickerAnt.tsx
packages/antd/src/TreeAnt.tsx
packages/antd/src/__tests__/__snapshots__/BoolAnt.test.tsx.snap
packages/antd/src/__tests__/__snapshots__/DatePickerAnt.test.tsx.snap
packages/antd/src/__tests__/__snapshots__/ManyOfAnt.test.tsx.snap
packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap
packages/antd/src/__tests__/__snapshots__/TimePickerAnt.test.tsx.snap
packages/antd/src/routing/NavLinkButtonAnt.tsx
packages/moxb/src/many-of/ManyOf.ts
packages/moxb/src/many-of/ManyOfImpl.ts

Many small improvements in the input widgets.
The outline:
- Make sure to always properly indicate the disabled state, and preferably also the reason
- Make sure to always display the help messages for choices (on OneOf / ManyOf), whenever possible
- ManyOf: add functions to test/set the selection status of the individual choices
- Add ManyOfSwitchAnt (a multi-select widget based on switches)
Please see the individual commit messages for details.

Input widget improvements

---

ChangeLog.md
packages/antd/src/BindAnt.tsx
packages/antd/src/BoolAnt.tsx
packages/antd/src/FormItemAnt.tsx

…instead of using a custom tooltip.
We used this tooltip for display various help messages.
But in some situations this doesn't work, so in those cases we used the browser's title attribute.
In the end we had a mixture of the two.
It seemed to be OK, but it turns out, that it some browsers the two thing looks quite differently,
which is confusing. So this PR deprecates the tooltip-based feature, and stops using it in widgets.
I haven't covered the Semantic UI widgets, because we don't really maintain them anyway.

Revert to the browser's native title feature for a uniform look

---

ChangeLog.md
packages/antd/src/OneOfAnt.tsx
packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap

When there is a OneOf or ManyOf widget, it's possible that there are multiple messages
that could be displayed at the same time:
- Help text for the individual choices
- The reason by a choice is disabled
- The reason why the whole widget is disabled.
Make sure that we display the messages according to the correct priorities.

Adjusted message priorities on OneOfAnt and OneOfButtonAnt

---

ChangeLog.md
packages/antd/src/NumericAnt.tsx
packages/antd/src/__tests__/__snapshots__/NumericAnt.test.tsx.snap

The model and the antd inputnumber component are prepared to handle non-integer values
with a fixed precision. But our NumericAnt parse functions didn't take this into consideration.
This restores that functionality

Fix handling non-integer values for NumericAnt

---

ChangeLog.md
packages/moxb/src/routing/TokenManagerImpl.ts
packages/moxb/src/routing/index.ts
packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts
packages/moxb/src/routing/location-manager/LocationManager.ts
packages/moxb/src/routing/location-manager/index.ts

Interface changes:
- Export new function: `urlToLocation()``
- New methods on `LocationManager`:
- `getPathTokensForLocation()`
- `getQueryForLocation`
- New parameters on existing methods on `LocationManager`
- `getNewLocationForPathAndQueryChange()` now accepts `dropPermanent`
- `getNewLocationForLinkProps()` now accepts `dropPermanent`
Internal changes:
- Relax the `TestLocation` interface
- `doPathTokensMatch` is now optional
- In `BasicLocationManagerImpl`
- The `getNewLocationForPathTokens()` method now expects a base location parameter
- In `TokenManagerImpl`:
- BUGFIX: in `_getLocationForTokenChangeOnMapping()`, really observer the `prevLocation` parameter

Small navigation improvements / fixes

---

ChangeLog.md
packages/antd/src/routing/NavLinkButtonAnt.tsx
packages/html/src/NavLink.tsx
packages/html/src/Redirect.tsx
packages/moxb/src/routing/TokenManager.ts
packages/moxb/src/routing/TokenManagerImpl.ts
packages/moxb/src/routing/index.ts
packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts
packages/moxb/src/routing/location-manager/LocationManager.ts
packages/moxb/src/routing/location-manager/index.ts
packages/moxb/src/routing/navigation-references/LinkGenerator.ts
packages/moxb/src/routing/url-arg/AnyUrlArgImpl.ts
packages/moxb/src/routing/url-arg/UrlArg.ts
packages/moxb/src/routing/url-arg/UrlArgImpl.ts
packages/moxb/src/routing/url-arg/UrlTokenImpl.ts
packages/moxb/src/routing/url-schema/HashBasedUrlSchema.ts
packages/moxb/src/routing/url-schema/NativeUrlSchema.ts
packages/moxb/src/routing/url-schema/QueryBasedUrlSchema.ts
packages/moxb/src/routing/url-schema/UrlSchema.ts
packages/moxb/src/routing/url-schema/__tests__/HashBasedUrlSchema.test.ts
packages/moxb/src/routing/url-schema/__tests__/NativeUrlSchema.test.ts
packages/moxb/src/routing/url-schema/__tests__/QueryBasedUrlSchema.test.ts

Two notes here:
1. This PR consists of two commits, which are orthogonal. The first one is only a refactoring; I moved the definition of a type into a single location, instead of defining it at multiple locations. This commit should be reviewed separately. The second commit implements the new feature, and in only impacts a single file.
2. This branch is not against the latest master, but against a master version before the NPM upgrade. This was necessary so that it is compatible with the latest VES code branch, which doesn't yet have the NPM upgrade. Therefore this should be rebased after that one is merged, too.

Add support for saving path upon redirects

---

ChangeLog.md
packages/moxb/src/impl.ts
packages/moxb/src/util/ShallowStructObservable.ts
packages/moxb/src/util/__tests__/ShallowStructObservable.test.ts

A helper to do to combine `observable.shallow` with `observable.struct`.
Useful when `observable.struct` causes too many reactions and
`observable` would make all children observable. It is used when new
versions of a object come form a rest call or a meteor subscription and\
you are interested in changes at the top level.

Added `ShallowStructObservable`

---

ChangeLog.md
packages/moxb/src/many-of/ManyOfImpl.ts
packages/moxb/src/one-of/OneOfImpl.ts

In most cases this was already working, but (for example) the type of that `bind` param of the `onSave` function was incomplete.
This type fixes the type definition.

Fix type parameter passing on OneOf and ManyOf
