Makefile, examples/Makefile, examples/antd/Application.ts, examples/antd/ApplicationImpl.ts, examples/antd/ApplicationUi.tsx, examples/antd/Store.ts, examples/antd/index.html, examples/antd/index.tsx, examples/index.html, examples/package-lock.json, examples/package.json, packages/antd/.gitignore, packages/antd/.npmignore, packages/antd/Makefile, packages/antd/jest/jestAdapter.js, packages/antd/jest/jestMockStyle.js, packages/antd/package-lock.json, packages/antd/package.json, packages/antd/peer-dependencies/package-lock.json, packages/antd/peer-dependencies/package.json, packages/antd/src/ActionUi.tsx, packages/antd/src/BindUi.tsx, packages/antd/src/__tests__/ActionUi.test.tsx, packages/antd/src/globals.d.ts, packages/antd/src/index.ts, packages/antd/tsconfig.json, packages/antd/tslint.json
Create a moxb package for ant design
=> ant design package

examples/antd/ApplicationUi.tsx, packages/antd/src/TextUi.tsx
Fix the `type` property for TextUi components with ant design.
=> TextUi component fix

ChangeLog.md, packages/antd/src/TableAnt.tsx, packages/meteor/src/MeteorTableImpl.ts, packages/moxb/src/i18n/__tests__/i18n.test.ts
Few enhancements of the MeteorTableImpl
=> fix meteor table

examples/antd/ApplicationAnt.tsx, examples/store/Application.ts, examples/store/ApplicationImpl.ts, package-lock.json, packages/antd/src/ActionAnt.tsx, packages/antd/src/DatePickerAnt.tsx, packages/antd/src/ManyOfAnt.tsx, packages/antd/src/TextAnt.tsx, packages/antd/src/index.ts, packages/moxb/src/date/Date.ts, packages/moxb/src/date/DateImpl.ts, packages/moxb/src/impl.ts, packages/moxb/src/types.ts, packages/semui/src/__tests__/__snapshots__/ActionUi.test.tsx.snap
Added a checkbox variant for the manyOf component.
Also added new date picker component for ant design.
=> ManyOf extensions

examples/antd/ApplicationAnt.tsx, examples/store/Application.ts, examples/store/ApplicationImpl.ts, packages/antd/src/DatePickerAnt.tsx, packages/antd/src/TimePickerAnt.tsx, packages/antd/src/index.ts, packages/moxb/src/impl.ts, packages/moxb/src/time/Time.ts, packages/moxb/src/time/TimeImpl.ts, packages/moxb/src/types.ts
I fixed the date picker value handling and added a time picker component for ant design.
=> Date picker fix

Makefile, examples/Makefile, examples/antd/ApplicationAnt.tsx, examples/package-lock.json, examples/package.json, examples/store/ApplicationImpl.ts, lerna.json, package-lock.json, package.json, packages/antd/package-lock.json, packages/antd/package.json, packages/meteor/package.json, packages/moxb/package.json, packages/semui/package.json
Messing with publication, strange peer dependencies problems and build...
=> Small fixes and new version published

ChangeLog.md, admin/makefiles/package.mk, packages/antd/package.json, packages/meteor/package.json, packages/moxb/package-lock.json, packages/semui/package.json
...some more makefile improvements -- there are some more reasons, why the `tsc` has to run.
=> Bug fix: run `tsc` when makefile etc change

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, examples/src/form/LoginFormUi.tsx, packages/antd/src/ActionAnt.tsx, packages/antd/src/__tests__/__snapshots__/ActionAnt.test.tsx.snap, packages/moxb/src/form/Form.ts, packages/moxb/src/form/FormImpl.ts, packages/moxb/src/form/__tests__/Form.test.ts
* Added original onSubmit event
* Fixed form errors
=> Fix form submit and errors

examples/Makefile, examples/package.json, examples/tsconfig.json, packages/antd/package.json, packages/antd/src/BindAnt.tsx, packages/antd/src/DatePickerAnt.tsx, packages/antd/src/ModalAnt.tsx, packages/antd/src/TableAnt.tsx, packages/antd/src/TimePickerAnt.tsx, packages/antd/src/__tests__/FormItemAnt.test.tsx, packages/antd/src/__tests__/TableAnt.test.tsx, packages/antd/tsconfig.json, packages/meteor/package.json, packages/moxb/package.json, packages/moxb/src/i18n/i18n.ts, packages/moxb/src/table/TableSortImpl.ts, packages/moxb/src/table/__tests__/TableImpl.test.ts, packages/moxb/src/util/idToDomId.ts, packages/moxb/src/util/toJSON.ts, packages/moxb/src/value/__tests__/ValueImplTest.test.ts, packages/moxb/tsconfig.json, packages/semui/package.json, packages/semui/src/ManyOfUi.tsx, packages/semui/src/OneOfUi.tsx, packages/semui/src/TablePaginationUi.tsx, packages/semui/tsconfig.json
... and clean up the resulting errors.
This is still not as tight as I would like it to be, for example in the examples app,
I don't get any warnings for unreachable code, etc.
=> Tighten up TS config a bit

examples/package.json, examples/src/app/Application.ts, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, examples/src/memtable/MemTableAnt.tsx, packages/antd/src/DatePickerAnt.tsx, packages/antd/src/TagAnt.tsx, packages/antd/src/TimePickerAnt.tsx, packages/antd/src/index.ts, packages/moxb/src/date/Date.ts, packages/moxb/src/date/DateImpl.ts, packages/moxb/src/time/Time.ts, packages/moxb/src/time/TimeImpl.ts, packages/moxb/src/value/ValueImpl.ts
Added an ant design component for tags display and fixed the Time- and DatePicker.
=> Add TagAnt component

packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts, packages/moxb/src/routing/url-arg/UrlArg.ts, packages/moxb/src/routing/url-arg/UrlArgImpl.ts, packages/moxb/src/routing/url-arg/UrlArgTypes.ts, packages/moxb/src/routing/url-arg/__tests__/UrlArgImpl.test.ts, packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeBoolean.test.ts, packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeOrderedStringArray.test.ts, packages/moxb/src/routing/url-arg/__tests__/UrlArgTypeUnorderedStringArray.test.ts
... since the parsers are never called for empty strings anyway.
=> Remove unwanted default value arg for url arg parsers

packages/moxb/src/form/FormImpl.ts
This makes it possible to supply a function for the `values` option, so that form fields can be dynamically calculated.
=> Support dynamic forms

packages/antd/src/OneOfAnt.tsx, packages/moxb/src/one-of/OneOf.ts
- Support HTML labels
- Support passing on more props to the actual AntD component
=> Enhance OneOf 

packages/meteor/src/MeteorMethod.ts, packages/meteor/src/index.ts
=> Provide an easy way for defining/calling Meteor methods

examples/src/app/Application.ts, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, package-lock.json, packages/antd/package.json, packages/antd/src/ConfirmAnt.tsx, packages/antd/src/FormItemAnt.tsx, packages/antd/src/LabelAnt.tsx, packages/antd/src/__tests__/__snapshots__/ConfirmAnt.test.tsx.snap, packages/antd/src/__tests__/__snapshots__/FormItemAnt.test.tsx.snap, packages/antd/src/index.ts, packages/html/src/ActionHtml.tsx, packages/moxb/src/impl.ts, packages/moxb/src/label/Label.ts, packages/moxb/src/label/LabelImpl.ts, packages/moxb/src/types.ts, packages/semui/package.json, packages/semui/src/LabelUi.tsx, packages/semui/src/index.ts
Adds markdown to ant design components
=> Markdown render support

packages/meteor/src/MeteorMethod.ts
... because it has a structure for transmitting errors for different fields.
=> Add an Error class that work well for forms

examples/src/app/ApplicationAnt.tsx, packages/antd/src/ActionAnt.tsx, packages/antd/src/routing/LinkAnt.tsx, packages/antd/src/routing/index.ts
Adds a simple span action link for menu items
=> ActionSpanAnt

packages/antd/src/__tests__/__snapshots__/ConfirmAnt.test.tsx.snap, packages/moxb/src/confirm/ConfirmImpl.ts, packages/moxb/src/confirm/__tests__/ConfirmImpl.test.ts
Remove the default text from the Confirm dialog
=> Comfirm bug fix

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, packages/antd/src/ActionAnt.tsx, packages/antd/src/BindAnt.tsx
Fixes: https://goessntl.atlassian.net/browse/VS-19
=> Toggle button component for ant design

packages/moxb/src/validation/ErrorMessage.ts
I had some improvement of error parsing.
=> Improved error extraction

packages/antd/src/index.ts, packages/moxb/src/many-of/ManyOf.ts, packages/moxb/src/many-of/ManyOfImpl.ts, packages/moxb/src/one-of/OneOf.ts, packages/moxb/src/one-of/OneOfImpl.ts
This allows other string based types to be used.
=> OneOf and ManyOf have now a type Parameter `T` (defaults to `string`)

packages/antd/src/routing/NavMenuBarAnt.tsx
Improved the menu ids
- eliminate `.` etc form menu id
- add Id to `noLink` Menu items
=> Better IDs

ChangeLog.md, packages/antd/src/routing/LinkAnt.tsx, packages/moxb/src/routing/TokenManager.ts, packages/moxb/src/routing/TokenManagerImpl.ts, packages/moxb/src/routing/index.ts, packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts, packages/moxb/src/routing/location-manager/LocationManager.ts, packages/moxb/src/routing/location-manager/index.ts, packages/moxb/src/routing/location-state-space/LocationDependentStateSpaceHandlerImpl.ts, packages/moxb/src/routing/url-arg/AnyUrlArgImpl.ts, packages/moxb/src/routing/url-arg/UrlArg.ts, packages/moxb/src/routing/url-arg/UrlArgImpl.ts, packages/moxb/src/routing/url-arg/UrlTokenImpl.ts, packages/moxb/src/routing/url-arg/index.ts
... and mess around with internal APIs.
Fix VS-329.
=> [VS-369] Fix LinkAnt with path token-based UrlArgs

examples/src/memtable/MemTable.ts, examples/src/memtable/MemTableAnt.tsx, examples/src/memtable/MemTableImpl.ts, examples/src/memtable/UserInfoAnt.tsx, examples/src/store/Store.ts, packages/moxb/src/routing/TokenManager.ts, packages/moxb/src/routing/TokenManagerImpl.ts
... in TokenManager.
Fixes VS-369
=> [VS-369] Support using multiple mappings at the same time

packages/antd/src/routing/LinkAnt.tsx, packages/moxb/src/routing/linking/index.ts, packages/moxb/src/routing/location-manager/BasicLocationManagerImpl.ts, packages/moxb/src/routing/location-manager/LocationManager.ts
... besides setting the path tokens (or URL arguments) directly.
=> LinkAnt: support directly adding and removing path tokens

ChangeLog.md, examples/src/app/ApplicationImpl.ts, packages/antd/src/ModalAnt.tsx, packages/antd/src/__tests__/ModalAnt.test.tsx, packages/antd/src/__tests__/__snapshots__/ModalAnt.test.tsx.snap, packages/moxb/src/modal/Modal.ts, packages/moxb/src/modal/ModalImpl.ts, packages/moxb/src/modal/__tests__/ModalImpl.test.ts, packages/semui/src/ModalUi.tsx
Fix [VS-372]
Non backward-compatible.
=> [VS-372] use object structure in modal actions

examples/src/app/ApplicationImpl.ts, examples/src/app/ApplicationMethods.ts, packages/antd/src/OneOfAnt.tsx, packages/antd/src/ToolTipAnt.tsx, packages/antd/src/__tests__/OneOfAnt.test.tsx, packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap, packages/moxb/src/routing/navigation-references/LinkGeneratorImpl.ts
Add the OneOfDropdownAnt component
Fix [VS-331]
=> [VS-331] add OneOfDropdownAnt component

ChangeLog.md, packages/antd/src/not-antd/Redirect.tsx, packages/antd/src/not-antd/index.ts, packages/antd/src/routing/LinkAnt.tsx
Introduce `NavRef` support to more UI components.
- Add `NavRef` support to `LinkAnt`
- Add support for redirecting directly to `NavRef`s
=> Add NavRef support to more components

ChangeLog.md, packages/antd/src/routing/LinkAnt.tsx, packages/antd/src/routing/index.ts
... which is useful when creating custom link components.
=> Export one more interface

package-lock.json, packages/antd/src/OneOfAnt.tsx, packages/meteor/package.json, packages/meteor/src/__mocks__/meteor/mongo.ts, packages/meteor/src/__tests__/utils.test.ts, packages/meteor/src/index.ts, packages/meteor/src/mongo/ActivityLogMiddleware.ts, packages/meteor/src/mongo/MongoCollectionMiddleware.ts, packages/meteor/src/mongo/MongoCollectionMiddlewareImpl.ts, packages/meteor/src/mongo/__tests__/ActivityLogMiddleware.test.ts, packages/meteor/src/mongo/index.ts, packages/meteor/src/utils.ts
=> [VS-118] add mongodb middlewares and ActivityLogMiddleware

packages/antd/src/TextAnt.tsx, packages/antd/src/__tests__/__snapshots__/TextAnt.test.tsx.snap
=> [VS-378] clear field on esc key press

packages/meteor/src/mongo/ActivityLogMiddleware.ts
Fix [VS-429]
Fix some type definitions for the activity logger.
=> [VS-429] Fix type definition in activity log

packages/moxb/src/impl.ts, packages/moxb/src/query/QueryFilter.ts, packages/moxb/src/query/QueryFilterImpl.ts, packages/moxb/src/query/__tests__/QueryFilterImpl.test.ts, packages/moxb/src/table/TableSearch.ts, packages/moxb/src/table/TableSearchImpl.ts, packages/moxb/src/table/__tests__/TableSearchImpl.test.ts, packages/moxb/src/types.ts
=> [VS-396] Support toggle condition for table search

Makefile, examples/package-lock.json, examples/package.json, jest.config.js, package-lock.json, package.json, packages/antd/package-lock.json, packages/antd/package.json, packages/antd/src/__mocks__/mobx-react.js, packages/antd/src/__tests__/__snapshots__/ConfirmAnt.test.tsx.snap, packages/antd/src/__tests__/__snapshots__/FormItemAnt.test.tsx.snap, packages/antd/src/__tests__/__snapshots__/ModalAnt.test.tsx.snap, packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap, packages/antd/src/__tests__/__snapshots__/TableAnt.test.tsx.snap, packages/antd/src/not-antd/UIFragment.ts, packages/antd/src/not-antd/UIFragmentSpec.ts, packages/antd/src/not-antd/isForwardRef.ts, packages/html/package-lock.json, packages/html/package.json, packages/meteor/package-lock.json, packages/meteor/package.json, packages/moxb/package-lock.json, packages/moxb/package.json, packages/moxb/src/table/TableSearchImpl.ts, packages/semui/package-lock.json, packages/semui/package.json
=> [VS-425] Update dependencies

ChangeLog.md, packages/antd/src/routing/NavStepsAnt.tsx
=> Fix a function scoping bug in NavStepAnt.

package-lock.json, package.json, packages/antd/package-lock.json, packages/antd/package.json, packages/antd/src/ToolTipAnt.tsx, packages/antd/src/__tests__/FormAnt.test.tsx, packages/antd/src/__tests__/TableAnt.test.tsx, packages/html/package-lock.json, packages/html/package.json, packages/meteor/package-lock.json, packages/meteor/package.json, packages/moxb/package-lock.json, packages/moxb/package.json, packages/semui/package-lock.json, packages/semui/package.json, packages/semui/src/ManyOfUi.tsx
=> [VS-528] Update npm packages

packages/moxb/src/routing/location-state-space/state-space/StateSpaceHandlerImpl.ts, packages/semui/src/ActionUi.tsx
Add show loading indicator on buttons when the operation is pending.
=> [TD-65] Add show loading indicator on buttons

ChangeLog.md, examples/package-lock.json, examples/package.json, examples/src/app/ApplicationAnt.tsx, examples/src/form/LoginFormAnt.tsx, package-lock.json, packages/antd/package-lock.json, packages/antd/package.json, packages/antd/src/BindAnt.tsx, packages/antd/src/OneOfAnt.tsx, packages/antd/src/TagAnt.tsx, packages/antd/src/TextAnt.tsx
Change how we import Icons from antd. The old way was causing performance issues.
Also update antd.
=> Upgrade antd to 4.4.0 and change ant-design imports not to import the whole package

ChangeLog.md, examples/src/app/Application.ts, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, packages/antd/src/TreeAnt.tsx, packages/antd/src/index.ts, packages/moxb/src/impl.ts, packages/moxb/src/tree/Tree.ts, packages/moxb/src/tree/TreeImpl.ts, packages/moxb/src/types.ts
Introduce Tree, TreeImpl and TreeAnt components.
=> Introduce Tree, TreeImpl and TreeAnt components

examples/package-lock.json, examples/package.json, examples/src/MenuStructure.tsx, examples/src/common/NavigationAnt.tsx, package-lock.json, package.json, packages/antd/package.json, packages/antd/src/not-antd/NavRefRedirect.tsx, packages/antd/src/not-antd/UIFragment.ts, packages/antd/src/not-antd/UIFragmentSpec.ts, packages/html/package-lock.json, packages/html/package.json, packages/moxb/src/routing/index.ts, packages/moxb/src/routing/navigation-references/LinkGenerator.ts, packages/moxb/src/routing/navigation-references/index.ts, packages/semui/package-lock.json, packages/semui/package.json
This changes fixes all the bugs I have been seeing.
=> More npm dependency and nav cleanup

ChangeLog.md, packages/antd/src/ToolTipAnt.tsx
=> Support indicating the pending state on ToolTipAnt

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, packages/html/src/CountingClock.tsx, packages/html/src/index.ts
This widget can display an amount of time, like a clock.
It can count forward, it can count backwards, and in can also show a fixed amount of time.
=> Add CountingClock widget

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, packages/antd/src/BoolAnt.tsx
This small PR enables to set boolean values via a toggle-switch component.
=> Introduce BoolSwitchAnt component

package-lock.json, packages/antd/src/ActionAnt.tsx, packages/moxb/package-lock.json, packages/moxb/package.json
... and remove unused imports.
=> Add missing dependencies

ChangeLog.md, examples/src/store/Store.ts, packages/moxb/src/routing/TokenManager.ts, packages/moxb/src/routing/TokenManagerImpl.ts
... so that is's also usable for applications with no menu system and sub-states.
=> Extend TokenManager for simple apps

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, packages/antd/src/OneOfAnt.tsx, packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap, packages/moxb/src/one-of/OneOf.ts
The two commits are independent.
Please see the examples.
=> Improve OneOfAnt: vertical layout + explanations

ChangeLog.md, packages/antd/src/OneOfAnt.tsx
=> OneOfFormAnt: add support for vertical layout of choices

ChangeLog.md, packages/antd/src/OneOfAnt.tsx
=> OneOfAnt and OneOfButtonAnt: add support for adding line breaks

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, packages/antd/src/ManyOfAnt.tsx, packages/antd/src/OneOfAnt.tsx, packages/antd/src/__tests__/__snapshots__/OneOfAnt.test.tsx.snap, packages/moxb/src/one-of/OneOf.ts
…. in OneOf... and ManyOf..… components.
=> Add support for disabling individual choices 

ChangeLog.md, packages/antd/src/routing/NavTabBarAnt.tsx
=> Fix errors on the console when trying to access an undefined tab

ChangeLog.md, examples/src/app/ApplicationAnt.tsx, packages/antd/src/BindAnt.tsx, packages/antd/src/ManyOfAnt.tsx, packages/antd/src/OneOfAnt.tsx
Implement this on all OneOf and ManyOf components where it was missing earlier
=> Improve displaying the per-option help messages 

ChangeLog.md, examples/src/MenuStructure.tsx, examples/src/memtable/MemTableAnt.tsx, packages/moxb/src/routing/TokenManager.ts, packages/moxb/src/routing/TokenManagerImpl.ts, packages/moxb/src/routing/location-state-space/state-space/StateSpace.ts, packages/moxb/src/routing/navigation-references/LinkGeneratorImpl.ts, packages/moxb/src/routing/url-arg/UrlTokenImpl.ts
- Filter out useless writes
- Introduce the (optional) vanishing tokens
=> Improve token mapper

ChangeLog.md, examples/src/app/Application.ts, examples/src/app/ApplicationAnt.tsx, examples/src/app/ApplicationImpl.ts, packages/antd/src/RateAnt.tsx, packages/antd/src/index.ts, packages/moxb/src/impl.ts, packages/moxb/src/rate/Rate.ts, packages/moxb/src/rate/RateImpl.ts, packages/moxb/src/types.ts
Check: https://ant.design/components/rate/
=> Introduce Rate and RateAnt components

ChangeLog.md, packages/moxb/src/routing/index.ts, packages/moxb/src/routing/url-arg/UrlArg.ts, packages/moxb/src/routing/url-arg/UrlArgImpl.ts, packages/moxb/src/routing/url-arg/__tests__/UrlArgImpl.test.ts, packages/moxb/src/routing/url-arg/index.ts
... which are pseudo UrlArgs wrapping another existing
UrlArgs.
Also did a bit of interface cleanp around UrlArgs.
=> Add support for DependantArgs

ChangeLog.md, packages/html/src/Anchor.tsx
... and Meta-click
Please close https://goessntl.atlassian.net/browse/VS-985 when merging.
=> Add support for opening links on new tabs using Ctrl-click 

packages/antd/src/RateAnt.tsx, packages/antd/src/routing/NavMenuBarAnt.tsx, packages/antd/src/routing/NavRadioButtonsBarAnt.tsx
... which were brought to the surface by the new TS version
=> Fix some TS errors

ChangeLog.md, packages/antd/src/SelectableConfirmAnt.tsx, packages/antd/src/index.ts, packages/moxb/src/confirm/Confirm.ts, packages/moxb/src/confirm/ConfirmImpl.ts, packages/moxb/src/confirm/SelectableConfirm.ts, packages/moxb/src/confirm/SelectableConfirmImpl.ts, packages/moxb/src/impl.ts, packages/moxb/src/types.ts
This component offers multiple actions to confirm a confirmation dialog.
=> Introduce SelectableConfirm
